name: Integration tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
      strategy:
        matrix:
          go-version: [ 1.18.x ]
          platform: [ ubuntu-latest ]
      runs-on: ${{ matrix.platform }}
      environment: 
        name: testing
      steps:
          - name: Install Go
            uses: actions/setup-go@v1
            with:
              go-version: ${{ matrix.go-version }}
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Run tests
            run:  go test -v ./...
