name: Integration tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
      strategy:
        matrix:
          go-version: [ 1.18.x ]
          platform: [ ubuntu-latest ]
      runs-on: ${{ matrix.platform }}
      env:
        LND_ADDRESS: ${{ secrets.LND_ADDRESS }}     
        MACAROON_HEX: ${{ secrets.MACAROON_HEX }}
        LNURL_ADDRESS: ${{ secrets.LNURL_ADDRESS }}
        ROOT_KEY: ${{ secrets.ROOT_KEY }}
        TEST_MACAROON: ${{ secrets.TEST_MACAROON }}
        TEST_PREIMAGE: ${{ secrets.TEST_PREIMAGE }}
      steps:
          - name: Install Go
            uses: actions/setup-go@v1
            with:
              go-version: ${{ matrix.go-version }}
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Run tests
            run:  go test -v ./...
